#spring:
#  h2:
#  console:
#      url:
#        enabled: true
#        datasource:
#        url: jdbc:h2:mem:user
#
#  server:
#    port: 9292
#
#
#
#
#
#
#
##    username: sa
##    password: password
##    driverClassName: org.h2.Driver
##  jpa:
##    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect